-- FINLONEXA role/region hierarchy and business-record authorization.
-- Review against the target database before running `supabase db push`.

create table if not exists public.regions (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint regions_name_not_blank check (btrim(name) <> ''),
  constraint regions_code_not_blank check (btrim(code) <> '')
);

create unique index if not exists regions_name_ci_key on public.regions (lower(name));
create unique index if not exists regions_code_ci_key on public.regions (lower(code));

alter table public.sales add column if not exists region_id bigint;
alter table public.sales drop constraint if exists sales_region_id_fkey;
alter table public.sales add constraint sales_region_id_fkey
  foreign key (region_id) references public.regions(id) on delete restrict;

-- Preserve existing deployments that used the legacy free-text `sales.region` field.
insert into public.regions (name, code, description)
select min(btrim(region)),
  upper(regexp_replace(min(btrim(region)), '[^a-zA-Z0-9]+', '-', 'g')) || '-' || substr(md5(lower(btrim(region))), 1, 6),
  'Migrated from the legacy sales.region field'
from public.sales
where nullif(btrim(region), '') is not null
group by lower(btrim(region))
on conflict do nothing;

update public.sales s set region_id = r.id
from public.regions r
where s.region_id is null and lower(btrim(s.region)) = lower(r.name);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.sales (
    first_name, last_name, email, user_id, administrator, role, designation,
    reports_to_user_id, region_id, region, area
  ) values (
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email, new.id,
    coalesce(new.raw_user_meta_data ->> 'role', 'bdo') = 'super_admin',
    case when new.raw_user_meta_data ->> 'role' in ('super_admin','head_of_sales','rsm','ssm','asm','bdo')
      then new.raw_user_meta_data ->> 'role' else 'bdo' end,
    new.raw_user_meta_data ->> 'designation',
    nullif(new.raw_user_meta_data ->> 'reports_to_user_id', '')::uuid,
    nullif(new.raw_user_meta_data ->> 'region_id', '')::bigint,
    new.raw_user_meta_data ->> 'region',
    new.raw_user_meta_data ->> 'area'
  );
  return new;
end $$;

create or replace function public.current_sales_id()
returns bigint language sql stable security definer set search_path = public
as $$ select id from public.sales where user_id = auth.uid() and disabled = false limit 1 $$;

create or replace function public.current_sales_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.sales where user_id = auth.uid() and disabled = false limit 1 $$;

create or replace function public.current_sales_region_id()
returns bigint language sql stable security definer set search_path = public
as $$ select region_id from public.sales where user_id = auth.uid() and disabled = false limit 1 $$;

create or replace function public.get_subordinate_sales_ids(root_sales_id bigint default public.current_sales_id())
returns setof bigint language sql stable security definer set search_path = public
as $$
  with recursive team(id) as (
    select s.id from public.sales s where s.id = root_sales_id and not s.disabled
      and (root_sales_id = public.current_sales_id() or public.current_sales_role() in ('super_admin','head_of_sales'))
    union all
    select child.id from public.sales child join team parent on child.reports_to_user_id =
      (select user_id from public.sales where id = parent.id)
    where not child.disabled
  ) select id from team
$$;

create or replace function public.can_access_sales_owner(owner_sales_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select case public.current_sales_role()
    when 'super_admin' then true
    when 'head_of_sales' then true
    when 'rsm' then exists (
      select 1 from public.sales owner
      where owner.id = owner_sales_id
        and owner.region_id = public.current_sales_region_id()
    )
    when 'ssm' then owner_sales_id in (select public.get_subordinate_sales_ids())
    when 'asm' then owner_sales_id in (select public.get_subordinate_sales_ids())
    when 'bdo' then owner_sales_id = public.current_sales_id()
    else false
  end
$$;

revoke all on function public.current_sales_id() from public;
revoke all on function public.current_sales_role() from public;
revoke all on function public.current_sales_region_id() from public;
revoke all on function public.get_subordinate_sales_ids(bigint) from public;
revoke all on function public.can_access_sales_owner(bigint) from public;
grant execute on function public.current_sales_id() to authenticated;
grant execute on function public.current_sales_role() to authenticated;
grant execute on function public.current_sales_region_id() to authenticated;
grant execute on function public.get_subordinate_sales_ids(bigint) to authenticated;
grant execute on function public.can_access_sales_owner(bigint) to authenticated;

create or replace function public.validate_sales_hierarchy()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  manager public.sales%rowtype;
  expected_role text;
begin
  if new.role in ('rsm', 'ssm', 'asm', 'bdo') and new.region_id is null then
    raise exception 'Region is required for role %', new.role;
  end if;
  if new.role in ('super_admin', 'head_of_sales') and new.region_id is not null then
    raise exception 'Region must be empty for role %', new.role;
  end if;
  if new.role = 'super_admin' then
    if new.reports_to_user_id is not null then raise exception 'Super Admin cannot report to another user'; end if;
    return new;
  end if;
  if new.reports_to_user_id is null then raise exception 'A manager is required for role %', new.role; end if;
  if new.reports_to_user_id = new.user_id then raise exception 'A user cannot report to themselves'; end if;

  select * into manager from public.sales where user_id = new.reports_to_user_id;
  if not found then raise exception 'Reports To user does not exist'; end if;
  if manager.disabled then raise exception 'A user cannot report to an inactive user'; end if;
  expected_role := case new.role when 'head_of_sales' then 'super_admin' when 'rsm' then 'head_of_sales'
    when 'ssm' then 'rsm' when 'asm' then 'ssm' when 'bdo' then 'asm' end;
  if manager.role <> expected_role then raise exception 'Invalid reporting hierarchy for role %', new.role; end if;
  if new.role in ('ssm', 'asm', 'bdo') and manager.region_id is distinct from new.region_id then
    raise exception 'Manager and subordinate must belong to the same region';
  end if;
  if tg_op = 'UPDATE' and old.region_id is distinct from new.region_id and exists (
    select 1 from public.sales child where child.reports_to_user_id = new.user_id
      and child.region_id is distinct from new.region_id
  ) then raise exception 'Reassign direct reports before changing this manager region'; end if;
  if exists (
    with recursive ancestors(user_id) as (
      select new.reports_to_user_id union all
      select s.reports_to_user_id from public.sales s join ancestors a on s.user_id = a.user_id
      where s.reports_to_user_id is not null
    ) select 1 from ancestors where user_id = new.user_id
  ) then raise exception 'Reporting hierarchy cannot contain cycles'; end if;
  return new;
end $$;

drop trigger if exists validate_sales_hierarchy_trigger on public.sales;
create constraint trigger validate_sales_hierarchy_trigger
after insert or update of role, reports_to_user_id, region_id, disabled on public.sales
deferrable initially immediate for each row execute function public.validate_sales_hierarchy();

create or replace function public.set_region_audit_fields()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.updated_at := now();
  if tg_op = 'INSERT' and new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end $$;
drop trigger if exists set_region_audit_fields_trigger on public.regions;
create trigger set_region_audit_fields_trigger before insert or update on public.regions
for each row execute function public.set_region_audit_fields();

create or replace function public.prevent_unsafe_region_delete()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if exists (select 1 from public.sales where region_id = old.id) then
    raise exception 'Region cannot be deleted because active CRM data is associated with it.';
  end if;
  return old;
end $$;
drop trigger if exists prevent_unsafe_region_delete_trigger on public.regions;
create trigger prevent_unsafe_region_delete_trigger before delete on public.regions
for each row execute function public.prevent_unsafe_region_delete();

alter table public.regions enable row level security;
drop policy if exists regions_select on public.regions;
drop policy if exists regions_admin_insert on public.regions;
drop policy if exists regions_admin_update on public.regions;
drop policy if exists regions_admin_delete on public.regions;
create policy regions_select on public.regions for select to authenticated using (true);
create policy regions_admin_insert on public.regions for insert to authenticated with check (public.current_sales_role() = 'super_admin');
create policy regions_admin_update on public.regions for update to authenticated using (public.current_sales_role() = 'super_admin') with check (public.current_sales_role() = 'super_admin');
create policy regions_admin_delete on public.regions for delete to authenticated using (public.current_sales_role() = 'super_admin');

-- Replace every existing business-table policy, including legacy USING (true) policies.
do $$
declare table_name text; policy_name text;
begin
  foreach table_name in array array['companies','contacts','deals','tasks','contact_notes','deal_notes'] loop
    if to_regclass('public.' || table_name) is null then continue; end if;
    execute format('alter table public.%I enable row level security', table_name);
    for policy_name in select pol.polname from pg_policy pol join pg_class c on c.oid=pol.polrelid
      join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=table_name
    loop execute format('drop policy %I on public.%I', policy_name, table_name); end loop;
    execute format('create policy %I on public.%I for select to authenticated using (public.can_access_sales_owner(sales_id))', table_name || '_scope_select', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.can_access_sales_owner(sales_id))', table_name || '_scope_insert', table_name);
    execute format('create policy %I on public.%I for update to authenticated using (public.can_access_sales_owner(sales_id)) with check (public.can_access_sales_owner(sales_id))', table_name || '_scope_update', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using (public.can_access_sales_owner(sales_id))', table_name || '_scope_delete', table_name);
  end loop;
end $$;

-- Sales-directory visibility is scope-aware; administration still flows through the service-role Edge Function.
alter table public.sales enable row level security;
do $$ declare policy_name text; begin
  for policy_name in select pol.polname from pg_policy pol join pg_class c on c.oid=pol.polrelid
    join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='sales'
  loop execute format('drop policy %I on public.sales', policy_name); end loop;
end $$;
create policy sales_scope_select on public.sales for select to authenticated using (
  public.current_sales_role() in ('super_admin','head_of_sales')
  or id = public.current_sales_id()
  or (public.current_sales_role() = 'rsm' and region_id = public.current_sales_region_id())
  or id in (select public.get_subordinate_sales_ids())
);

create or replace view public.region_stats with (security_invoker = true) as
select r.*,
  count(s.id) filter (where not s.disabled) as user_count,
  count(s.id) filter (where s.role='rsm' and not s.disabled) as rsm_count,
  count(s.id) filter (where s.role='ssm' and not s.disabled) as ssm_count,
  count(s.id) filter (where s.role='asm' and not s.disabled) as asm_count,
  count(s.id) filter (where s.role='bdo' and not s.disabled) as bdo_count
from public.regions r left join public.sales s on s.region_id=r.id group by r.id;
grant select, insert, update, delete on public.regions to authenticated;
grant select on public.region_stats to authenticated;
grant usage, select on sequence public.regions_id_seq to authenticated;

-- Summary/activity views must execute with caller permissions so base-table RLS is preserved.
do $$ declare view_name text; begin
  foreach view_name in array array['companies_summary','contacts_summary','activity_log'] loop
    if to_regclass('public.' || view_name) is not null then
      execute format('alter view public.%I set (security_invoker = true)', view_name);
    end if;
  end loop;
end $$;
