-- FINLONEXA leads: ownership is protected by the existing centralized scope helper.
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  first_name text not null check (btrim(first_name) <> ''), last_name text,
  company_name text, email text, phone text, source text,
  status text not null default 'new' check (status in ('new','contacted','qualified','unqualified','converted')),
  notes text, sales_id bigint not null references public.sales(id) on delete restrict,
  region_id bigint references public.regions(id) on delete restrict,
  created_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  converted_at timestamptz, converted_contact_id bigint, converted_company_id bigint, converted_deal_id bigint
);
create index if not exists leads_sales_created_idx on public.leads (sales_id, created_at desc);
create index if not exists leads_region_status_idx on public.leads (region_id, status);
create or replace function public.set_lead_scope() returns trigger language plpgsql security definer set search_path=public as $$
declare owner_region bigint;
begin
  if not public.can_access_sales_owner(new.sales_id) then raise exception 'Cannot assign lead outside your CRM scope'; end if;
  select region_id into owner_region from public.sales where id=new.sales_id and disabled=false;
  if owner_region is null then raise exception 'Lead owner must be an active regional sales user'; end if;
  new.region_id := owner_region; new.updated_at:=now(); if tg_op='INSERT' then new.created_by_user_id:=coalesce(new.created_by_user_id,auth.uid()); end if; return new;
end $$;
create trigger leads_scope_before_write before insert or update on public.leads for each row execute function public.set_lead_scope();
alter table public.leads enable row level security;
create policy leads_select on public.leads for select to authenticated using (public.can_access_sales_owner(sales_id));
create policy leads_insert on public.leads for insert to authenticated with check (public.can_access_sales_owner(sales_id));
create policy leads_update on public.leads for update to authenticated using (public.can_access_sales_owner(sales_id)) with check (public.can_access_sales_owner(sales_id));
create policy leads_delete on public.leads for delete to authenticated using (public.can_access_sales_owner(sales_id));
grant select,insert,update,delete on public.leads to authenticated; grant usage,select on sequence public.leads_id_seq to authenticated;
